### PR TITLE
A lot more configure capability

### PR DESCRIPTION
**Pull request by lindsayad**
Allow MetaPhysicL to be configured with a current TIMPI installation or with a "future" TIMPI installation that we believe will be present by the time anyone runs `make check`. If the user specifies that they want a future installation we check to see whether MPI can be detected in an effort to do as much verification as we can.

### CODE REVIEW

**Comment by lindsayad** [comment]
Uh did Travis just stop supporting `g++-7` or is some weird failure happening?
```
$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install g++-7

Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package g++-7
E: Couldn't find any package by regex 'g++-7'
```

**Comment by roystgnr** [comment]
Got to be a weird failure.  They deprecate by Ubuntu version, not one package at a time.

**Comment by lindsayad** [comment]
I'm testing it right now on libMesh. I'll report back how it did. All local configuration testing went well (e.g. don't set CXX but have MPIHOME, have CXX and MPIHOME, don't have either CXX OR MPIHOME but have mpicxx in PATH)

**Comment by lindsayad** [comment]
Ok, I verified that if I run `configure --with-future-timpi-dir=$LIBMESH_INSTALL_PREFIX` from libMesh using TIMPI from https://github.com/libMesh/TIMPI/pull/13, then I can run `make check` in libMesh and get the parallel testing in `MetaPhysicL`

**Comment by lindsayad** [comment]
If I don't have libMeshTIMPI#13 then I get a run-time error because MetaPhysicL can't find PETSc

**Comment by lindsayad** [comment]
@roystgnr If you don't hear any shouts from you, I'm going to merge this

**Pull request merged**
