### PR TITLE
Put complex function declarations in dynamicsparsenumberbase_decl

### PR DESCRIPTION
**Pull request by lindsayad**
This will enable a cleaner libMesh/libmesh#1946

### CODE REVIEW

**Comment by roystgnr** [comment]
Thanks!

**Comment by roystgnr** [comment]
Are you going to need a new tag for the libMesh side of things?  This is a minor change, but I wouldn't mind an excuse to put out a new release and bump up the library numbering to resolve #27

**Comment by lindsayad** [comment]
A tag would be great after #29

**Comment by lindsayad** [comment]
Currently on travel, but I noticed today that the derivative for std::norm for the non-complex dual number case is wrong. It would be nice to get that fix into the release...

**Pull request merged**
