### PR TITLE
Eliminate some memmove/memcpy

### PR DESCRIPTION
**Pull request by lindsayad**
This restores the multiply and division dualnumber operation
sequence to what it was before #11, however, with the key check
of whether the two operands are the same object. If they are,
it is a bug to first multiply(divide) the derivatives by the value
and then execute another statement. In this latter case, you really
do need a "temporary" to hold the expression.

In the former case, however, creating a "temporary" is unnecessarily
expensive, especially in the case of static derivative storage.
For static derivative storage, it doesn't matter if you have a
function with move semantics...you're still going to be copying
its contents in the body of operator+(DN &&, const DN &)
in the case of multiplication or operator-(DN &&,const DN &) in
the case of division.

### CODE REVIEW

**Comment by lindsayad** [comment]
I profiled this on my MOOSE test case, and the `if-else` check doesn't appear to cause any slowness.

**Comment by roystgnr** [comment]
> the if-else check doesn't appear to cause any slowness

I'd hope not; an inline function testing for equality between it's arguments' addresses?  The only way that can't be resolved at compile time is if its arguments are being passed along as arguments to an outer non-inline function, which probably never happens.

**Comment by roystgnr** [comment]
Oh, hell.  Looking at this closer, it looks like you broke some of the mixed cases in #51.  Let me see if I can set up a failure case to demonstrate.

**Comment by roystgnr** [comment]
No, false alarm, everything's working fine, and it looks like it'll be working fine here too.  Thanks!

**Pull request merged**
