### PR TITLE
DualNumber construction/assignment from DualNumberSurrogate

### PR DESCRIPTION
**Pull request by lindsayad**
Needed for operations like:
```c++
DualNumber<double> new_dn = NotADuckDualNumber<TensorValue<double>>(TensorValue<double>())(0, 0)
```

### CODE REVIEW

**Comment by roystgnr** [comment]
You're certain this needs to be an implicit rather than explicit constructor?  I'm tempted to agree but I've gotten myself in trouble that way before.

**Comment by lindsayad** [comment]
Hmm...this was motivated by some work I was doing in libMesh last week, and I think the work I was doing there could have used explicit. And I definitely agree that `explicit` would eliminate some possible unintended consequences. I would be tempted to make it `explicit` for now, and then see if I run into a use case later that requires implicit.

**Comment by roystgnr** [comment]
> I would be tempted to make it explicit for now, and then see if I run into a use case later that requires implicit.

Let's try that?  Thanks for indulging my paranoia.

**Comment by lindsayad** [comment]
I made the change to explicit...just squashed into the original commit

**Comment by roystgnr** [comment]
Thanks!

**Pull request merged**
