### PR TITLE
Add some complex functions for dual numbers

### PR DESCRIPTION
**Pull request by lindsayad**

### CODE REVIEW

**Comment by lindsayad** [comment]
What kind of `complex` implementation is being used for the clang build?! I can't use a `const` copy constructor? I have system headers on my Mac and the llvm headers from our MOOSE package, and both of those `complex` implementations would work with the new code I wrote, e.g. there are `const` `real()` and `imag()` methods.

**Comment by roystgnr** [comment]
It looks like the Travis clang is using gcc 4.8.something libstdc++ headers...

IIRC around that time gcc stopped supporting real() and imag() methods that returned references... but that doesn't seem to have anything to do with the errors here.  It looks as if it's failing to resolve ```std::real(const double &)```!

**Comment by roystgnr** [comment]
Why is it trying to specialize ```'std::real<double, MetaPhysicL::NumberArray<2,
      std::complex<double> > >'```???  There are two types there even, not one!

**Comment by lindsayad** [comment]
Ok, it looks like the headers must have been fixed in `libstdc++-4.9`. Now things are working with `g++-7` and `clang-3.6`. Both cover c++14

**Comment by roystgnr** [comment]
Victory; thanks!

**Pull request merged**
