### PR TITLE
Initial parallel packing support

### PR DESCRIPTION
**Pull request by lindsayad**
- Adds optional dependency on TIMPI
- Implements `StandardType` and `Packing` for `DualNumber` and `DynamicSparseNumberArray`. More types to follow

### CODE REVIEW

**Comment by roystgnr** [comment]
Looks good.  In the longer run we should add a --with-timpi case to the Travis CI, or finally get moosebuild running directly on MetaPhysicL too.

**Comment by lindsayad** [comment]
> Looks good. In the longer run we should add a --with-timpi case to the Travis CI, or finally get moosebuild running directly on MetaPhysicL too.

Maybe we can get moosebuild spun up when we're both in Idaho next week

**Comment by lindsayad** [comment]
@roystgnr and maybe @jwpeterson I'm looking for ideas on how to run the ` MetaPhysicL` parallel tests (which require `TIMPI`) when running `make check` in `libMesh`? Or perhaps put more simply...how in the world when configuring from `libMesh`, can I make `MetaPhysicL` `configure` detect `TIMPI`. The `m4` that I just put in here only works with an installed `TIMPI` library but this wouldn't exist if I'm just building from `libMesh`

**Comment by roystgnr** [comment]
Damn, that's a tricky one.  We'd have to, at the very least, have a configure option to the effect of ```--with-timpi-take-my-word-for-it``` to let the detection continue even when it finds no library to link to (although we could still check for headers).  Then on top of that we'd need to make sure the linking worked both pre- and post-install ... although I guess that part's not critical, since we currently don't even bother to install the unit tests, and they're the only things that need to link to TIMPI since everything else except the runtime versioning info is header-only.

**Comment by lindsayad** [comment]
> `--with-timpi-take-my-word-for-it`

😆 

> although we could still check for headers

How? There won't be any installed headers just like there won't be any installed libraries at the time of configure. I'm imagining an argument like `--with-timpi-src` that could be checked at configure time for headers

**Comment by lindsayad** [comment]
Also something like `--with-timpi-src` would only grant `MetaPhysicL` the ability to pull in TIMPI headers. It wouldn't be able to detect any dependencies that TIMPI itself has. So the person who would want parallel capability from `MetaPhysicL` would have to make sure they're detecting MPI independently (which will probably always be the case, certainly libMesh does that) so that any program compiled with `-Imetaphysicl/parallel_dualnumber.h -Itimpi/standard_type.h etc.` also has `-I/path/to/mpi`

**Comment by lindsayad** [comment]
I think that if `--with-timpi-take-my-word-for-it` is supplied then `MetaPhysicL` would need to perform its own configure time checks for MPI headers, and then for `MetaPhysicL` `tests` also perform configure time checks for MPI libs.

**Pull request merged**
